[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/imovel/:codigo"
  to = "/imovel.html"
  status = 200

[[redirects]]
  from = "/parceiros"
  to = "/parceiros.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
